#MODULES: ["gs_default"]
exp_name: ma2c1_add5_flow2_10seed_eps_6_1024_group_traffic #ddpg_share_lr4 atten_T2_ac_tmp_100_60_4_group_traffic #ddpg_100_group_traffic
scenario: group_traffic
softmax: False

# hyperparams of algorithm
len_phase12: 30000
len_attention_buffer: 10000
goal_step_size: 5
num_groups: 2
latent_dims: 64

max_episode_len: 60
num_episodes: 250000
num_adversaries: 0
good_policy: maddpg
adv_policy: maddpg
#lr: 1.e-2
lr: 1.e-4
gamma: .95
#batch_size: 64
batch_size: 1024
num_units: 64

models_dir: ''
save_rate: 10000
load_dir: ''

restore: False
display: False

benchmark_iters: 100000
benchmark_dir: './benchmark_files'

tf_log: True
tf_dir: ''

video: True
video_rate: 1000

use_ma2c: True
simple_ddpg: False #True
simple_ddpg_share: False
maddpg_self: False
algo: mfqq  #choices={'ac', 'mfac', 'mfq', 'dqn', 'm_mfq', 'mf_Double_q', 'Double_dqn'}
misc: False




